export const INIT_PRODUCTS_LIST_PAGE = 'PLP/INIT_PRODUCTS_LIST_PAGE';
export const RENDER_PRODUCT_DESCRIPTION_PAGE =
	'PDP/RENDER_PRODUCT_DESCRIPTION_PAGE';
export const RENDER_CURRENCIES = 'ACTION_BAR/RENDER_CURRENCIES';
