export const INIT_APP = 'APP/INIT_APP';

export const INIT_PRODUCTS_LIST_PAGE = 'PLP/INIT_PRODUCTS_LIST_PAGE';
export const RENDER_PRODUCT_PAGE ='PDP/RENDER_PRODUCT_PAGE';
export const CLEAR_PRODUCT_PAGE = 'PDP/CLEAR_PRODUCT_PAGE';
export const RENDER_CURRENCIES = 'ACTION_BAR/RENDER_CURRENCIES';
export const SET_CURRENCY = 'ACTION_BAR/SET_CURRENCY';

export const INIT_CURRENCY_SWITCHER =
	'CURRENCY_SWITCHER/INIT_CURRENCY_SWITCHER';
export const SWITCH_ACTUAL_CURRENCY =
	'CURRENCY_SWITCHER/SWITCH_ACTUAL_CURRENCY';
export const OPEN_CURRENCY_LIST = 'CART_OVERLAY/OPEN_CURRENCY_LIST';
export const CLOSE_CURRENCY_LIST = 'CART_OVERLAY/CLOSE_CURRENCY_LIST';

export const INIT_NAVBAR = 'NAVBAR/INIT_NAVBAR';
export const INIT_CURRENT_CATEGORY = 'CATEGORY_PAGE/INIT_CURRENT_CATEGORY';
export const RENDER_CATEGORY_PAGE = 'CATEGORY_PAGE/RENDER_CATEGORY_PAGE';
export const ADD_ITEM_TO_CART = 'CART/ADD_ITEM_TO_CART';
export const REMOVE_ITEM_FROM_CART = 'CART/REMOVE_ITEM_FROM_CART';
export const INCREASE_ITEMS_QUANTATY = 'CART/INCREASE_ITEMS_QUANTATY';
export const DECREASE_ITEMS_QUANTATY = 'CART/DEINCREASE_ITEMS_QUANTATY';

export const ADD_NOTIFICATION = 'TOAST/ADD_NOTIFICATION';
export const DELETE_NOTIFICATION = 'TOAST/DELETE_NOTIFICATION';

export const OPEN_OVERLAY = 'CART_OVERLAY/OPEN_OVERLAY';
export const CLOSE_OVERLAY = 'CART_OVERLAY/CLOSE_OVERLAY';

export const UPDATE_ACTUAL_CURRENCY_IN_CART = 'CART/UPDATE_ACTUAL_CURRENCY_IN_CART';
export const SUM_TOTAL_PRICE = 'CART/SUM_TOTAL_PRICE';
export const INIT_GALLERY = 'GALLERY/INIT_GALLERY';
export const NEXT_PICTURE = 'GALLERY/NEXT_PICTURE';
export const PREV_PICTURE = 'GALLERY/PREV_PICTURE';